### ISSUE TITLE
About data prepare

### ISSUE THREAD

**Issue by liuzhihua-web** [liw95/SGLoc#1]
Thank you for your excellent work.
I am unable to download the pre-trained model in SPVNAS due to the orgin download link is out of work . Would you mind sending me the pre-trained model you downloaded? my email is 2779333079@qq.com.Thank you very much

**Comment by liw95** [comment]
In fact, any semantic segmentation methods are possible. I have emailed you the SPVNAS weights.

**Comment by liuzhihua-web** [comment]
I have received your email.Thank you very much


| |
Liu
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/29/2024 14:48 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [liw95/SGLoc] About data prepare (Issue #1) |

In fact, any semantic segmentation methods are possible. I have emailed you the SPVNAS weights.
